### ISSUE TITLE
Mettre le texte en noir

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/bordeaux-iut-de-bordeaux#40]
https://bordeaux-iut-de-bordeaux.web.deuxfleurs.fr/formations/genie-biologique/agronomie/

<img width="1164" alt="Capture d’écran 2024-10-14 à 09 25 53" src="https://github.com/user-attachments/assets/e8523438-3898-4fa0-9f29-dd75b10a99c8">

<img width="1492" alt="Capture d’écran 2024-10-14 à 09 26 21" src="https://github.com/user-attachments/assets/c5fa9b99-3b9a-4176-8dd7-6ed5913b3dc5">

**Comment by arnaudlevy** [comment]
https://bordeaux-iut-de-bordeaux.web.deuxfleurs.fr/formations/carrieres-sociales/animation-sociale-et-socioculturelle/

<img width="1118" alt="Capture d’écran 2024-10-14 à 09 27 27" src="https://github.com/user-attachments/assets/5a7c0418-52fa-4d50-8fca-8a0f2478af44">

<img width="1491" alt="Capture d’écran 2024-10-14 à 09 27 09" src="https://github.com/user-attachments/assets/fd5abea5-b567-426e-bb69-d3702ae857a5">

**Comment by alexisben** [comment]
Prêt pour déploiement ça va arriver
