### ISSUE TITLE
Puces pas calées

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/bordeaux-iut-de-bordeaux#41]
<img width="232" alt="Capture d’écran 2024-10-14 à 09 28 03" src="https://github.com/user-attachments/assets/67b77b82-6b6c-4dc8-a32a-5a0fad904bf7">

Les puces en ponctuation marginale, pourquoi pas, mais il faut que la verticale du texte soit calée

**Comment by alexisben** [comment]
Vérifier avec le passage de cette PR : https://github.com/osunyorg/theme/pull/670

**Comment by alexisben** [comment]
on doit être bon pour ça !
