### ISSUE TITLE
Titre des blocks

### ISSUE THREAD

**Issue by alexisben** [osunyorg/bordeaux-iut-de-bordeaux#7]
Les titres des blocks peuvent être variables en fonction du contenu de la page (h2 ou h3)

<img width="317" alt="image" src="https://github.com/osunyorg/bordeaux-iut-de-bordeaux/assets/4630530/e3f10b03-93a9-42e4-992c-227362e0ed04">

**Comment by Clararigaud** [comment]
fixed
