### ISSUE TITLE
Bloc campus : bouton étrange

### ISSUE THREAD

**Issue by alexisben** [osunyorg/bordeaux-iut-de-bordeaux#9]
Le bouton n'est pas cliquable !

<img width="387" alt="image" src="https://github.com/osunyorg/bordeaux-iut-de-bordeaux/assets/4630530/260a83a0-5224-48f2-b5b6-06ee92293c75">

C'est très bizarre ce bouton injecté avec un pseudo-élément, c'est pas robuste. Il faut ajouter une option au config.yml pour que ce bloc puisse afficher / masquer le bouton.

**Comment by Clararigaud** [comment]
Oopsie il faudrait probablement ajouter cette option au thème ! 
Proposition d'ajout d'option au bloc ( donc en admin ) en restant iso avec l'option dejà disponible dans le hero.

coucou @Olivia206  et @alexisben et @arnaudlevy  pour le design et le back

**Comment by arnaudlevy** [comment]
Pas besoin d'option d'admin, il n'y a pas d'affordance autre (flèche ou soulignement) donc le bouton est tout le temps là !

**Comment by Clararigaud** [comment]
PR #537
